POST /api1 HTTP/1.1
Content-Type: application/json
Host: localhost:3000

[
    {
        "id": 1,
        "url": "http://localhost:3000/api1",
        "editMemo": false,
        "memo": "",
        "delay": "",
        "fibonacci": 0,
        "shutdown": false,
        "error": false,
        "code": 500,
        "timeout": false,
        "resultcode": "",
        "resulttime": "",
        "errorresult": "",
        "setheaders": false,
        "headers": "{\"Content-Type\":\"application/json\"}",
        "apicalls": 0,
        "apicallmethod": [],
        "apicallurls": [],
        "apicallheaders": [],
        "apicallbody": [],
        "apicalltimes": [],
        "apicallresults": [],
        "lognums": 0,
        "loglevels": [],
        "logdetails": [],
        "processenv": "",
        "apiserchkeywords": [],
        "processenvsearchkeyword": "",
        "apicallstatuses": []
    },
    {
        "id": 2,
        "url": "http://localhost:3000/api2",
        "editMemo": false,
        "memo": "",
        "delay": "",
        "fibonacci": 0,
        "shutdown": false,
        "error": false,
        "code": 500,
        "timeout": false,
        "resultcode": "",
        "resulttime": "",
        "errorresult": "",
        "setheaders": false,
        "headers": "{\"Content-Type\":\"application/json\"}",
        "apicalls": 0,
        "apicallmethod": [],
        "apicallurls": [],
        "apicallheaders": [],
        "apicallbody": [],
        "apicalltimes": [],
        "apicallresults": [],
        "lognums": 0,
        "loglevels": [],
        "logdetails": [],
        "processenv": "",
        "apiserchkeywords": [],
        "processenvsearchkeyword": "",
        "apicallstatuses": []
    }
]